### ISSUE TITLE
go根据环境变量走不同的配置

### ISSUE THREAD

**Issue by 0x7765** [0x7765/note#2]
# app config file
```yaml
Dev:
  Port: 10086
  LogLevel: "debug"
  Pprof: true
  Servers:
    - 1.2.3.4
    - 4.3.2.1
    - 5.6.7.8

Prod:
  Port: 8888
  LogLevel: "info"
  Pprof: false
  Servers:
    - 1.2.3.4
    - 4.3.2.1
    - 5.6.7.8
```

# 获取环境变量
```go
package common

import "os"

const (
	envKey = "mode" // 环境变量 key
	Dev    = "Dev"
	Prod   = "Prod"
)

var env string

func init() {
	env = os.Getenv(envKey)
}

func IsDev() bool {
	return Dev == env
}

func IsProd() bool {
	return Prod == env
}
```

# 获取配置文件路径

参考 #1 

# 解析

```go
package conf

import (
	"fmt"
	"gindemo/common"
	"github.com/spf13/viper"
	"os"
)

type AppConfig struct {
	Port     int      //  service port
	LogLevel string   // log level
	Pprof    bool     // is enable pprof
	Servers  []string // cluster
}

var (
	AConfig AppConfig
)

func InitAppConfig() {
	parse(common.GetConfPath() + "appconfig.yaml")
}

func parse(file string) {
	var (
		vv  *viper.Viper
		err error
	)
	mode := common.Prod
	if common.IsDev() {
		mode = common.Dev
	}

	v := viper.New()
	// config file
	v.SetConfigFile(file)
	if err = v.ReadInConfig(); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to load app config: %s, %+v\n", file, err)
		goto ERROR
	}

	if vv = v.Sub(mode); vv == nil {
		fmt.Fprintf(os.Stderr, "Failed to parse config sub module: %s\n", mode)
		goto ERROR
	}

	if err = vv.Unmarshal(&AConfig); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to unmarshal app config: %s\n", err)
		goto ERROR
	}
	fmt.Printf("a conf:%+v\n", AConfig)
	return

ERROR:
	os.Exit(-1)
}
```
